# Generated by Django 5.1.4 on 2025-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'male')], max_length=200)),
                ('childname', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('childgender', models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], max_length=200)),
                ('vaccinated', models.CharField(choices=[('done', 'done'), ('pending', 'pending')], max_length=200, null=True)),
            ],
        ),
    ]
