# Generated by Django 5.1.4 on 2025-01-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='childgender',
            field=models.CharField(choices=[('Girl', 'Girl'), ('Boy', 'Boy')], default='Boy', max_length=200),
        ),
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=200),
        ),
        migrations.AlterField(
            model_name='parent',
            name='vaccinated',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Done', max_length=200, null=True),
        ),
    ]
