# Generated by Django 5.1.4 on 2025-01-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_parent_childgender_alter_parent_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='payment',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='parent',
            name='payment_Mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Upi', 'Upi')], default='Cash', max_length=200),
        ),
        migrations.AddField(
            model_name='parent',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
