# Generated by Django 5.1.4 on 2025-01-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_parent_payment_parent_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
