# Generated by Django 5.1.4 on 2025-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_parent_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('comments', models.TextField(max_length=250, null=True)),
            ],
        ),
    ]
