# Generated by Django 5.1.4 on 2025-01-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
