# Generated by Django 5.1.4 on 2025-01-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
